name: Haskell CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '8.8.4' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'
      - name: Stack Cache 
        uses: actions/cache@v3
        with:
          path: .stack-work
          key:          ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}
          restore-keys: ${{ runner.os }}-stack-work

      - name: Install dependencies
        run: |
          stack update
        
      - name: Run tests
        run: stack test
