name: Haskell CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '8.8.4' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: 'latest'
          stack-no-global: true
      - name: Stack Cache 
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
      
      - name: Install dependencies
        run: |
          stack update

      - name: List files
        run: ls
        
      - name: Run tests
        run: stack test --no-terminal --stack-yaml stack.yaml
