name: Haskell CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '8.8.4'
          enable-stack: true
          stack-version: 'latest'
          stack-no-global: true
      - name: Stack Cache 
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
      
      - name: Install dependencies
        run: |
          stack update

      - name: Run tests
        run: stack test --no-terminal --stack-yaml stack.yaml

      - name: Create documentation
        run: |
          mkdir docs
          stack haddock --haddock-arguments=--odir=docs

      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/
